# https://github.com/nanxiaobei/hugo-paper

baseURL = 'https://andybug.com/'
title = "andybug"
author = "Andrew Fields"
copyright = "Copyright © 2024, Andrew Fields."
languageCode = "en-US"
enableRobotsTXT = true
enableInlineShortcodes = true

theme = 'paper'

#[markup]
#  [markup.goldmark]
#    [markup.goldmark.renderer]
#      unsafe = true

[params]
color = "linen"
monoDarkIcon = true
rss = true
github = 'andybug'


[menu]

[[menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 10

[[menu.main]]
identifier = "articles"
name = "Articles"
url = "/articles/"
weight = 9

[taxonomies]
#category = "categories"
tag = "tags"
series = "series"

